project:
  type: website
  output-dir: docs

website:
  title: "China Science Vector"
  image: "" #img/my_image.jpg
  favicon: "img/favicon.png" 

  navbar:
    background: primary
    pinned: false
    logo: "" #"img/favicon.png"
    left:
      - href: bcas/bcas.qmd
        text: BCAS
      - href: bcae/about_bcae.qmd
        text: BCAE 
   # social media handles
    right:
        - icon: linkedin
          href: www.linkedin.com/in/dzmitry-mazanik-a84b51246
        - icon: envelope
          aria-label: email
          href: "mailto:dmitrymazanik42@gmail.com" 
  
  sidebar:
    - id: id-bcas
      title: "Bulletin of Chinese Academy of Sciences"
      style: docked
      background: none
      contents:
        - bcas/about_bcas.qmd
        - bcas/bcas_dataset_scraping.ipynb
        - bcas/bcas_eda.ipynb
        - bcas/bcas_topic_model.ipynb
        - bcas/bcas_topic_analysis.ipynb
      collapse-level: 2
  search: 
    location: navbar

  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright 2024, Dzmitry Mazanik" 

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: false
    smooth-scroll: true
    grid: 
      body-width: 1000px
      sidebar-width: 300px
      margin-width: 300px

fig-cap-location: top
fig-align: center
