---
title: "Welcome to China Science Vector"
reference-location: margin

---

Hello there! I'm Dzmitry, a Belarusian China Studies analyst based at the Center for System Analysis & Strategic Research[^1] of the National Academy of Sciences. My primary focus lies in China's Science & Technology and industrial policy.

In an era where information about China is paradoxically both abundant and increasingly restricted, I'am learning data science techniques to gain deeper insights into Chinese technology. This approach allows me to navigate the complex landscape of China's tech sector more effectively.[^2]

China Science Vector is my little laboratory for China and technology data analysis case studies. We like .csv files a lot!

Through my work here, I aim to:

• Uncover and share valuable insights about China

• Demonstrate the power of data science in China Studies

• Share and learn new data techniques.

I welcome your engagement! Whether you have suggestions, are interested in collaboration, or notice mistakes, please don't hesitate to reach out.

[^1]: We have a very cool logo! People are cool too.
[^2]: At least I hope not to drown in tech solutionism...