---
title: CAS & Science Policy
sidebar: id-bcas
toc: false
reference-location: margin
citation-location: margin  
---


The Chinese Academy of Sciences (中国科学院, CAS) is China's premier scientific organization and is recognized as one of the national high-end think tanks (国家高端智库).[^1] CAS publishes its' own Bulletin (中国科学院院刊, BCAS), which functions not only as a scientific journal but also as a platform for scientists and experts to share opinions on science and technology issues. The Bulletin was referenced in the South China Morning Post[^2], highlighting insights from Zheng Yongnian of the Chinese University of Hong Kong regarding the "middle-technology trap" and the existing gap between China and advanced Western countries.

Another case is provided by the Stanford University DigiChina project, which highlights that articles in the Bulletin of the Chinese Academy of Sciences (BCAS) feature recommendations from Chinese scholars on how to reconstruct the country's innovation system and reorganize the science and technology bureaucracy.[^3]

[^1]: For more details, read the MERICS report [Whispering advice, roaring praises: The role of Chinese think tanks under Xi Jinping](https://blog.merics.org/en/report/whispering-advice-roaring-praises-role-chinese-think-tanks-under-xi-jinping).
[^2]: See the article ['Can China pull itself out of the ‘middle technology trap’ and challenge US at the top?'](https://www.scmp.com/news/china/science/article/3254360/can-china-pull-itself-out-middle-technology-trap-and-challenge-us-top) by Holly Chik, Dannie Peng, and Zhang Tong. 
[^3]: Read ['How to Rebuild China’s ‘Innovation System’–According to Officials and Scholars'](https://digichina.stanford.edu/work/how-to-rebuild-chinas-innovation-system-according-to-officials-and-scholars/) by Zac Haluza.

# Chinese Academy of Sciences

As described on the official website,[^4] CAS was founded alongside the establishment of the PRC in 1949. CAS serves as the country's premier institution for natural sciences and technology, playing a pivotal role in advancing scientific research and contributing to economic and social development.

CAS has played a pivotal role in advancing scientific research in China by assembling distinguished scientists and creating premier research institutions. During the reform and opening-up period, CAS not only promoted international collaboration but also initiated vital reforms in research management. Its efforts in translating research into practical applications have significantly supported the development of high-tech enterprises, underscoring its influence on China's technological advancement and economic growth.

Key contributions of CAS include:

- Advancements in national security through developments in aerospace and defense technologies.
- Innovations in computing and internet technologies, including the creation of China’s first supercomputers and internet infrastructure.
- Progress in chemical and industrial technologies.
- Contributions to oil exploration and production theories.
- Leadership in drug innovation and agricultural technology.
- Notable achievements in life sciences and mathematics.

CAS has also expanded its educational programs, establishing a graduate education system that has trained many scientists who engage in both national and international scientific efforts. The academy plays a significant role in advising on national policy and strategic planning.

Today, CAS encompasses numerous research institutes and educational institutions, focusing on innovation-driven development. Its goals include "meeting national needs while pursuing academic excellence", with a vision of establishing China as a leading global scientific power by its centennial in 2049.

CAS is also focused on achieveing "Two Centenary Goals" (两个一百年). The goals should be achieved with the "Leading Action" plan (“率先行动”计划) which will implement a "two-step" development strategy:

> The first step is to comprehensively complete the tasks of "Innovation 2020" by around 2020, which marks the 100th anniversary of the founding of the Communist Party, and to basically achieve the "Four Leading" goals. This will ensure that national strategic scientific and technological forces play a leading role in implementing the innovation-driven development strategy and building an innovative country.

>The second step is to fully realize the "Four Leading" goals by around 2030, laying a solid foundation for establishing China as a global scientific and technological powerhouse by the 100th anniversary of the founding of the People's Republic of China and the Chinese Academy of Sciences. This will provide strong support for the great rejuvenation of the Chinese nation and the realization of the Chinese Dream.

**Hou Jianguo** (侯建国) is the President (院长) and Secretary of the Party Leadership Group (党组书记)[^5] of CAS. Born in 1959, Hou Jianguo is a male Han Chinese, a member of the CCP, he is an academician of both CAS and the Academy of Sciences for the Developing World. He has served in various significant roles, including member of the Central Committees of the Communist Party and the National People's Congress. Hou Jianguo is a physical chemist and nanomaterials expert, his research focuses on nanomaterials, single-molecule physics, and scanning tunneling microscopy. He has received numerous awards for his contributions, including national and provincial honors.

[^4]: CAS description can be accessed [here](https://www.cas.cn/zz/yk/201410/t20141016_4225142.shtml).
[^5]: Actually, this position is more important in the power structure of the academies in China.


**Wu Zhaohui** (吴朝晖) is the Vice President and Deputy Secretary of the Party Leadership Group (Ministerial Level). Born in 1966, professor Wu Zhao Hui is a male Han Chinese, also a member of the CCP. He is an academician of CAS and the Academy of Sciences for the Developing World. He is also an alternate member of the 19th and 20th Central Committees of the Communist Party. Wu Zhaohui has extensive research experience in computer science, technology, and artificial intelligence. He has received several awards, including the Second Prize for National Technological Invention and the Second Prize for National Scientific and Technological Progress.

Interestingly, the third person listed in the leadership is **Sun Yegang** (孙也刚), who is not a scientist, but the Head of the Discipline Inspection and Supervision Team and Member of the Party Leadership Group of the Chinese Academy of Sciences.

Profile: Born in 1963, Sun Ye Gang is a male Han Chinese and a member of the Communist Party. He holds a doctorate and is a member of the Central Commission for Discipline Inspection of the Communist Party for the 19th and 20th terms.

Current Roles: He serves as the head of the Central Commission for Discipline Inspection and National Supervisory Commission stationed at the Chinese Academy of Sciences, as well as a member of the Academy's Party Leadership Group.

# Bulletin of Chinese Academy of Sciences

The Bulletin of the Chinese Academy of Sciences (BCAS) is positioned on its website as the core media outlet for China's national science think tank (国家科学思想库核心媒体). It emphasizes key strategic issues in the country’s scientific policy, including the interplay of science, technology, and socio-economic development, as well as evaluations of significant frontiers and interdisciplinary research trends. BCAS aims to offer scientific support for national macro-strategic decision-making and to effectively disseminate scientific thinking and spirit to the broader public. 

Research reports published in BCAS are typically authored by academicians from CAS and the Chinese Academy of Engineering, as well as senior scientists, including institute directors and laboratory supervisors, alongside policymakers and members of the Communist Party. These articles are expected to embody a strategic perspective, national significance, international outlook, and a sense of historical responsibility (“战略高度、国家层面、国际视野、历史担当”).

The development model of BCAS is structured as “Five in One” (五位一体模式):

- Hard Copy (纸刊): special topics are planned with some of the columns being permanent, which “serves the development of science and technology and supports the country’s economic and social development”.
- Forum (论坛): CAS hosts “Strategy and Decision-making High-level Forum” (战略与决策高层论坛).
- New Media (新媒体): the materials of the journal are available both on WeChat and the Internet. Authors state that “the annual read of WeChat high-end users exceeds 500,000 and the read of electronic journals exceeds 300,000 per issue”.
- Internal Report (内部报告): scientists prepare strategic reports for decision-makers.
- Research and Consultation (调研咨询): “The editorial team of BCAS is entrusted to organise strategic scientists and experts in related fields to carry out research and consultation activities for enterprises, localities, and related institutions”.

Multiple articles are reprinted by important newspapers and periodicals such as Xinhua Digest each year,while its’ series “Top Ten Scientific Advances in China" is recognized by the scientific and technological community. BCAS’s comprehensive impact factor has ranked among the best in similar journals according to CNKI.
The conceptual role of BCAS is divided into three stages:

- Journal of CAS (中国科学院机关刊), 1986—2005: communication within CAS and externally with ministries or institutions.
- Exploration Stage of Think Tank Media (智库媒体探索阶段), 2005—2016: core media of the national science think tank.
- Think Tank Platform Construction (智库平台建设), 2017—present: diversified communication platform for national high-end S&T think tank.

# Dataset Structure

CAS clearly plays a vital role in shaping China's science and technology policymaking and decision-making support. The limited coverage of BCAS in media and research projects presents a compelling case for exploration—specifically, to understand the perspectives of China's scientific experts and bureaucrats.

BCAS is an open-access journal, with all articles available digitally since its inception in 1986. These can be accessed on the [official website](http://www.bulletin.cas.cn). 

Through web scraping techniques we composed the dataset containing key metadata (both in Chinese and English) for, including:

- Issue
- Views
- Downloads
- Titles 
- Authors
- Affiliations
- Abstracts
- Keywords
- Associated fund projects
- Similar article references

The dataset consists of 7045 publications, dated between 1986–2023. For topic modeling we used 6509 entries due to irrelevance of some publications to the S&T domain.[^6]

The textual data (titles, keywords, abstracts, and similar references) was used to build a topic model of the dataset with a total of 100 topics to preserve the granularity. To get a broader picture we grouped these topics by science subfield, field, and domain, according to the Science-Metrix classification.[^7]

[^6]: For more details see [Building Topic Model](2_bcas_topic_model_quarto.ipynb) .
[^7]: https://www.science-metrix.com/classification/